// apps/v2/app/src/lib/gui/SavedSearches.svelte
<script lang="ts">
	import {
		getSavedSearchesForActor,
		searchVaultForActor,
		type SearchContentType,
		type SearchFilter,
		type SearchSourceId,
	} from '@dndtools/v2-core';
	import { useRuntime } from '$lib/state/runtime-context';

	// SRCH-003 / SRCH-004: the FILTERS + SAVED SEARCHES surface. The user filters search by source, content
	// type, tag, folder, and free text; the result lists the active filters + the matching VISIBLE hits, all
	// rendered from the single actor-filtered search query (SRCH-003). The DM additionally saves, pins, and
	// deletes named searches; the saved-search list re-runs each filter LIVE for the viewing actor, so a
	// player never sees a dm-only saved search NOR a result a saved search references that has since been
	// hidden (SRCH-004 AC2 / SRCH-003 AC4). This surface dispatches command intents for saved-search CRUD;
	// the AUTHORITATIVE visibility + DM-only authoring enforcement lives in the Processing Core (Contract 1).
	const runtime = useRuntime();

	const actor = $derived(runtime.state.permissions.actors[runtime.activeActorId] ?? null);
	const isDm = $derived(actor?.role === 'dm');

	const SOURCES: SearchSourceId[] = ['local-markdown', 'obsidian', 'google-docs'];
	const TYPES: SearchContentType[] = ['note', 'object', 'poi'];
	const sourceLabels: Record<SearchSourceId, string> = {
		'local-markdown': 'Local',
		obsidian: 'Obsidian',
		'google-docs': 'Google Docs',
	};
	const typeLabels: Record<SearchContentType, string> = {
		note: 'Note',
		object: 'Object',
		poi: 'Map POI',
	};

	// Ad-hoc filter (local UI state only). An empty filter matches all visible artifacts.
	let query = $state('');
	let selectedSources = $state<SearchSourceId[]>([]);
	let selectedTypes = $state<SearchContentType[]>([]);
	let tagsText = $state('');
	let folder = $state('');

	function toggle<T>(list: T[], value: T): T[] {
		return list.includes(value) ? list.filter((v) => v !== value) : [...list, value];
	}

	function buildFilter(): SearchFilter {
		const tags = tagsText
			.split(',')
			.map((t) => t.trim())
			.filter((t) => t !== '');
		const filter: SearchFilter = {};
		if (query.trim()) filter.query = query.trim();
		if (selectedSources.length > 0) filter.sources = [...selectedSources];
		if (selectedTypes.length > 0) filter.contentTypes = [...selectedTypes];
		if (tags.length > 0) filter.tags = tags;
		if (folder.trim()) filter.folder = folder.trim();
		return filter;
	}

	const result = $derived(
		searchVaultForActor(
			runtime.state.content,
			runtime.state.maps,
			runtime.state.permissions,
			runtime.state.session,
			runtime.activeActorId,
			buildFilter(),
		),
	);

	// The saved searches visible to the running actor, each run LIVE. A dm-only saved search is absent for
	// a player (SRCH-004 AC2); each run re-evaluates for THIS actor (no stale leak — SRCH-003 AC4).
	const savedSearches = $derived(
		getSavedSearchesForActor(
			runtime.state.content,
			runtime.state.maps,
			runtime.state.permissions,
			runtime.state.session,
			runtime.activeActorId,
		),
	);

	let error = $state<string | null>(null);
	let saveName = $state('My search');
	let saveVisibility = $state<'dm-only' | 'player-visible'>('dm-only');

	async function dispatch(command: Parameters<typeof runtime.dispatch>[0]): Promise<boolean> {
		error = null;
		const outcome = await runtime.dispatch(command);
		if (outcome.status === 'rejected') {
			error = outcome.rejection.message;
			return false;
		}
		return true;
	}

	async function saveCurrentFilter(): Promise<void> {
		if (!saveName.trim()) {
			error = 'Enter a name for the saved search.';
			return;
		}
		await dispatch({
			type: 'content.create-saved-search',
			actorId: runtime.activeActorId,
			payload: {
				name: saveName.trim(),
				filter: buildFilter(),
				visibility: saveVisibility,
			},
		});
	}

	async function togglePinned(searchId: string, pinned: boolean): Promise<void> {
		await dispatch({
			type: 'content.pin-saved-search',
			actorId: runtime.activeActorId,
			payload: { searchId, pinned },
		});
	}

	async function deleteSaved(searchId: string): Promise<void> {
		await dispatch({
			type: 'content.delete-saved-search',
			actorId: runtime.activeActorId,
			payload: { searchId },
		});
	}
</script>

<section data-testid="saved-searches" aria-label="Filters and saved searches">
	<h2>Filters &amp; saved searches</h2>
	<p class="meta">
		Filter search by source, content type, tag, folder, and text. Results — and any count — include only
		what your visibility permits. The DM can save, pin, and delete searches for recurring workflows.
	</p>

	{#if error}
		<p class="error" role="alert" data-testid="saved-search-error">{error}</p>
	{/if}

	<form
		data-testid="search-filter-form"
		onsubmit={(event) => {
			event.preventDefault();
		}}
	>
		<label>
			Search text
			<input data-testid="search-query" bind:value={query} autocomplete="off" />
		</label>
		<fieldset data-testid="search-sources">
			<legend class="meta">Source</legend>
			{#each SOURCES as source (source)}
				<label class="check">
					<input
						type="checkbox"
						data-testid={`search-source-${source}`}
						checked={selectedSources.includes(source)}
						onchange={() => (selectedSources = toggle(selectedSources, source))}
					/>
					{sourceLabels[source]}
				</label>
			{/each}
		</fieldset>
		<fieldset data-testid="search-types">
			<legend class="meta">Content type</legend>
			{#each TYPES as type (type)}
				<label class="check">
					<input
						type="checkbox"
						data-testid={`search-type-${type}`}
						checked={selectedTypes.includes(type)}
						onchange={() => (selectedTypes = toggle(selectedTypes, type))}
					/>
					{typeLabels[type]}
				</label>
			{/each}
		</fieldset>
		<label>
			Tags (comma-separated)
			<input data-testid="search-tags" bind:value={tagsText} autocomplete="off" />
		</label>
		<label>
			Folder
			<input data-testid="search-folder" bind:value={folder} autocomplete="off" />
		</label>
	</form>

	<p class="meta" data-testid="search-count">
		{result.totalCount} matching result{result.totalCount === 1 ? '' : 's'}
	</p>

	{#if result.sourceStatus.some((s) => s.freshness !== 'fresh')}
		<ul class="status-list" data-testid="search-source-status">
			{#each result.sourceStatus.filter((s) => s.freshness !== 'fresh') as status (status.source)}
				<li data-testid={`search-source-status-${status.source}`}>
					<span class="meta">{sourceLabels[status.source]}: {status.freshness}</span>
				</li>
			{/each}
		</ul>
	{/if}

	{#if result.hits.length === 0}
		<p class="meta" data-testid="search-empty">No visible results match your filter.</p>
	{:else}
		<ol class="result-list" data-testid="search-results">
			{#each result.hits as hit (`${hit.type}:${hit.id}`)}
				<li data-testid={`search-result-${hit.type}-${hit.id}`}>
					<span class="meta">{typeLabels[hit.type]}</span>
					<strong> {hit.title}</strong>
				</li>
			{/each}
		</ol>
	{/if}

	{#if isDm}
		<form
			class="save-form"
			data-testid="save-search-form"
			onsubmit={(event) => {
				event.preventDefault();
				void saveCurrentFilter();
			}}
		>
			<label>
				Save this filter as
				<input data-testid="save-search-name" bind:value={saveName} autocomplete="off" />
			</label>
			<label>
				Visibility
				<select data-testid="save-search-visibility" bind:value={saveVisibility}>
					<option value="dm-only">DM only</option>
					<option value="player-visible">Player-visible</option>
				</select>
			</label>
			<button type="submit" data-testid="save-search-submit">Save search</button>
		</form>
	{/if}

	<h3>Saved searches</h3>
	{#if savedSearches.length === 0}
		<p class="meta" data-testid="saved-search-empty">No saved searches you can see.</p>
	{:else}
		<ul class="saved-list" data-testid="saved-search-list">
			{#each savedSearches as saved (saved.id)}
				<li data-testid={`saved-search-${saved.id}`}>
					<strong data-testid={`saved-search-name-${saved.id}`}>{saved.name}</strong>
					<span class="meta" data-testid={`saved-search-visibility-${saved.id}`}>
						({saved.visibility})
					</span>
					<span class="meta" data-testid={`saved-search-result-count-${saved.id}`}>
						— {saved.result.totalCount} result{saved.result.totalCount === 1 ? '' : 's'}
					</span>
					{#if saved.pinned}
						<span class="meta" data-testid={`saved-search-pinned-${saved.id}`}>pinned</span>
					{/if}
					{#if isDm}
						<button
							type="button"
							data-testid={`saved-search-pin-${saved.id}`}
							onclick={() => void togglePinned(saved.id, !saved.pinned)}
						>
							{saved.pinned ? 'Unpin' : 'Pin'}
						</button>
						<button
							type="button"
							data-testid={`saved-search-delete-${saved.id}`}
							onclick={() => void deleteSaved(saved.id)}
						>
							Delete
						</button>
					{/if}
				</li>
			{/each}
		</ul>
	{/if}
</section>

<style>
	.error {
		color: var(--color-danger, #b00020);
	}
	.meta {
		color: var(--color-text-muted, #666);
	}
	.check {
		display: inline-flex;
		gap: var(--space-1, 0.25rem);
		align-items: center;
		margin-right: var(--space-2, 0.5rem);
	}
	.result-list,
	.saved-list,
	.status-list {
		list-style: none;
		padding: 0;
		display: flex;
		flex-direction: column;
		gap: var(--space-1, 0.25rem);
	}
	.save-form {
		display: flex;
		flex-direction: column;
		gap: var(--space-1, 0.25rem);
		margin: var(--space-2, 0.5rem) 0;
	}
</style>

// apps/gm-react/src/screens/knowledge/SavedSearches.tsx
import { useMemo, useState } from 'react';
import { actorCanAuthorContent, getSavedSearchesForActor, type SearchFilter } from '@dndtools/core';
import { Button, Checkbox, Chip, Field, Icon, Input, Select, Toaster } from '../../ds';
import { T } from '../../app/screen-kit';
import { useRuntime } from '../../runtime/RuntimeContext';
import { VIS_CHIP, visibilityOptions } from './shared';
import { useI18n, type MessageKey } from '../../i18n';

/**
 * RC-KNW-2.1 — the saved-search half of the Knowledge filters panel: name the current criteria, pin
 * them to the Command Center, rename them, delete them, apply them back into the editor.
 *
 * A saved search stores the QUERY and never a result. `getSavedSearchesForActor` re-evaluates each
 * stored filter LIVE for the reading actor, so the count beside a saved search is that actor's own
 * visible matches — a `dm-only` saved search is absent from a player's list entirely (SRCH-004 AC2),
 * and a `player-visible` one can never serve an item that has since been hidden. Save/pin/rename/
 * delete are the real `content.*-saved-search` commands; a rejection is shown, never swallowed.
 */
export function SavedSearches({
	filter,
	onApply,
}: {
	/** The criteria currently in the filter editor — what "Save this search" persists. */
	filter: SearchFilter;
	/** Load a stored filter back into the editor. */
	onApply: (filter: SearchFilter) => void;
}) {
	const { t } = useI18n();
	const runtime = useRuntime();
	const actorId = runtime.defaultActorId;
	const canAuthor = actorCanAuthorContent(runtime.state.permissions, actorId);

	const [busy, setBusy] = useState(false);
	const [saveName, setSaveName] = useState('');
	const [saveVisibility, setSaveVisibility] = useState('dm-only');
	const [savePinned, setSavePinned] = useState(false);
	// Renaming happens inline — a modal prompt would take the list away from the DM mid-edit.
	const [renamingId, setRenamingId] = useState<string | null>(null);
	const [renameValue, setRenameValue] = useState('');

	const saved = useMemo(
		() =>
			getSavedSearchesForActor(
				runtime.state.content,
				runtime.state.maps,
				runtime.state.permissions,
				runtime.state.session,
				actorId,
			),
		[runtime.state, actorId],
	);
	// Pinned first (they are the Command Center's tiles), then the core's stable id order.
	const ordered = useMemo(
		() => [...saved.filter((s) => s.pinned), ...saved.filter((s) => !s.pinned)],
		[saved],
	);

	/** Dispatch one saved-search command, surfacing a rejection rather than reporting a false success. */
	async function run(
		type: string,
		payload: Record<string, unknown>,
		fallback: MessageKey,
	): Promise<boolean> {
		setBusy(true);
		try {
			const outcome = await runtime.dispatch({ type, actorId, payload } as Parameters<
				typeof runtime.dispatch
			>[0]);
			if (outcome.status === 'accepted') return true;
			Toaster.error(outcome.rejection.message);
			return false;
		} catch (error) {
			Toaster.error(error instanceof Error ? error.message : t(fallback));
			return false;
		} finally {
			setBusy(false);
		}
	}

	async function saveCurrent() {
		const ok = await run(
			'content.create-saved-search',
			{
				name: saveName.trim(),
				filter,
				visibility: saveVisibility,
				sharedWith: [],
				pinned: savePinned,
			},
			'knowledge.filters.saveFailed',
		);
		if (ok) {
			setSaveName('');
			setSavePinned(false);
		}
	}

	async function commitRename(searchId: string) {
		const name = renameValue.trim();
		if (name === '') return;
		const ok = await run(
			'content.update-saved-search',
			{ searchId, name },
			'knowledge.filters.renameFailed',
		);
		if (ok) setRenamingId(null);
	}

	return (
		<>
			{canAuthor && (
				<div style={{ display: 'grid', gap: 10, borderTop: `1px solid ${T.bd}`, paddingTop: 12 }}>
					<Field label={t('knowledge.filters.saveName')} required>
						<Input
							value={saveName}
							data-testid="filters-save-name"
							onChange={(e: { target: { value: string } }) => setSaveName(e.target.value)}
						/>
					</Field>
					<Field label={t('knowledge.filters.saveVisibility')}>
						<Select
							value={saveVisibility}
							data-testid="filters-save-visibility"
							options={visibilityOptions(t)}
							onChange={(e: { target: { value: string } }) => setSaveVisibility(e.target.value)}
						/>
					</Field>
					<Checkbox
						checked={savePinned}
						label={t('knowledge.filters.savePin')}
						data-testid="filters-save-pin"
						onChange={setSavePinned}
					/>
					<div>
						<Button
							variant="primary"
							size="sm"
							icon="check"
							disabled={busy || saveName.trim() === ''}
							data-testid="filters-save"
							onClick={saveCurrent}
						>
							{t('knowledge.filters.save')}
						</Button>
					</div>
				</div>
			)}

			<div style={{ display: 'grid', gap: 8, borderTop: `1px solid ${T.bd}`, paddingTop: 12 }}>
				<span style={{ font: `600 13px ${T.sans}` }}>{t('knowledge.filters.saved')}</span>
				{ordered.length === 0 ? (
					<p
						style={{ font: `12.5px/1.6 ${T.sans}`, color: T.ter, margin: 0 }}
						data-testid="filters-saved-empty"
					>
						{t('knowledge.filters.savedEmpty')}
					</p>
				) : (
					<ul
						style={{ listStyle: 'none', margin: 0, padding: 0, display: 'grid', gap: 8 }}
						data-testid="filters-saved-list"
					>
						{ordered.map((entry) => (
							<li
								key={entry.id}
								data-testid={`filters-saved-${entry.id}`}
								style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}
							>
								{entry.pinned && <Icon name="pin" size={14} color={T.acc} />}
								{renamingId === entry.id ? (
									<>
										<Input
											value={renameValue}
											data-testid="filters-rename-input"
											style={{ flex: 1, minWidth: 140 }}
											onChange={(e: { target: { value: string } }) =>
												setRenameValue(e.target.value)
											}
										/>
										<Button
											variant="primary"
											size="sm"
											icon="check"
											disabled={busy || renameValue.trim() === ''}
											data-testid="filters-rename-save"
											onClick={() => commitRename(entry.id)}
										>
											{t('common.action.save')}
										</Button>
										<Button
											variant="ghost"
											size="sm"
											icon="close"
											onClick={() => setRenamingId(null)}
										>
											{t('common.action.cancel')}
										</Button>
									</>
								) : (
									<>
										<span style={{ font: `600 13px ${T.sans}`, flex: 1, minWidth: 120 }}>
											{entry.name}
										</span>
										{/* The count is the LIVE re-run of the stored filter for this actor. */}
										<span style={{ font: `12px ${T.sans}`, color: T.ter }}>
											{t('knowledge.filters.matches', { count: entry.result.totalCount })}
										</span>
										<Chip tone="neutral">
											{t(
												VIS_CHIP[entry.visibility] === 'dm-only'
													? 'common.visibility.dmOnly'
													: 'knowledge.visPlayers',
											)}
										</Chip>
										<Button
											variant="ghost"
											size="sm"
											icon="search"
											data-testid={`filters-apply-${entry.id}`}
											onClick={() => onApply(entry.filter)}
										>
											{t('knowledge.filters.apply')}
										</Button>
										{canAuthor && (
											<>
												<Button
													variant="ghost"
													size="sm"
													icon="pin"
													disabled={busy}
													aria-pressed={entry.pinned}
													data-testid={`filters-pin-${entry.id}`}
													onClick={() =>
														run(
															'content.pin-saved-search',
															{ searchId: entry.id, pinned: !entry.pinned },
															'knowledge.filters.pinFailed',
														)
													}
												>
													{t(entry.pinned ? 'knowledge.filters.unpin' : 'knowledge.filters.pin')}
												</Button>
												<Button
													variant="ghost"
													size="sm"
													icon="edit"
													disabled={busy}
													data-testid={`filters-rename-${entry.id}`}
													onClick={() => {
														setRenamingId(entry.id);
														setRenameValue(entry.name);
													}}
												>
													{t('knowledge.filters.rename')}
												</Button>
												<Button
													variant="ghost"
													size="sm"
													icon="delete"
													disabled={busy}
													data-testid={`filters-delete-${entry.id}`}
													onClick={() =>
														run(
															'content.delete-saved-search',
															{ searchId: entry.id },
															'knowledge.filters.deleteFailed',
														)
													}
												>
													{t('common.action.delete')}
												</Button>
											</>
										)}
									</>
								)}
							</li>
						))}
					</ul>
				)}
			</div>
		</>
	);
}
