// apps/gm-react/src/ds/components/forms/TagInput.tsx
export interface TagInputProps extends Omit<
	React.InputHTMLAttributes<HTMLInputElement>,
	'value' | 'onChange'
> {
	value?: string[];
	onChange?: (tags: string[]) => void;
	placeholder?: string;
	maxTags?: number;
	disabled?: boolean;
	inputStyle?: React.CSSProperties;
	chipStyle?: React.CSSProperties;
}

import React from 'react';
import { Icon } from '../core/Icon';

function normalizeTags(raw: readonly unknown[] = []) {
	const seen = new Set();
	const out: string[] = [];
	for (const v of raw) {
		if (typeof v !== 'string') continue;
		const tag = v.trim();
		const lower = tag.toLowerCase();
		if (!tag || seen.has(lower)) continue;
		seen.add(lower);
		out.push(tag);
	}
	return out;
}

function splitTags(raw = '') {
	return String(raw)
		.split(',')
		.map((t) => t.trim())
		.filter(Boolean);
}

function addUnique(base: string[] = [], next: string[] = [], maxTags = Infinity) {
	const seen = new Set(base.map((t) => t.toLowerCase()));
	const out = base.slice();
	for (const tag of next) {
		if (out.length >= maxTags) break;
		const value = tag.trim();
		if (!value) continue;
		const key = value.toLowerCase();
		if (seen.has(key)) continue;
		seen.add(key);
		out.push(value);
		if (out.length >= maxTags) break;
	}
	return out;
}

/**
 * TagInput — tokenized text input that emits discrete, de-duplicated tags.
 * Press Enter or comma to add the draft, Backspace on an empty draft to remove
 * the last tag, and blur to commit the pending draft value.
 */
export function TagInput({
	value = [],
	onChange,
	placeholder = 'Add a tag and press Enter',
	maxTags = Infinity,
	disabled = false,
	style,
	inputStyle,
	chipStyle,
	onBlur,
	onFocus,
	onKeyDown,
	...rest
}: TagInputProps) {
	const tags = normalizeTags(value).slice(0, maxTags);
	const [draft, setDraft] = React.useState('');

	const push = (next: string[]) => {
		const nextTags = addUnique(tags, next, maxTags);
		if (nextTags.length === tags.length) return;
		onChange?.(nextTags);
	};

	const remove = (index: number) => {
		if (disabled) return;
		const next = tags.filter((_, i) => i !== index);
		onChange?.(next);
	};

	const commitDraft = () => {
		const next = splitTags(draft);
		if (!next.length) {
			setDraft('');
			return;
		}
		setDraft('');
		push(next);
	};

	const handleKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
		if (disabled) return;
		if (event.nativeEvent.isComposing) return;
		if (event.key === 'Enter' || event.key === ',') {
			event.preventDefault();
			commitDraft();
		}
		if (event.key === 'Backspace' && !draft.trim() && tags.length > 0) {
			remove(tags.length - 1);
		}
		onKeyDown?.(event);
	};

	const handleFocus = (event: React.FocusEvent<HTMLInputElement>) => {
		event.currentTarget.style.borderColor = 'var(--color-border-focus)';
		event.currentTarget.style.boxShadow = '0 0 0 3px var(--color-interactive-selected)';
		onFocus?.(event);
	};

	const handleBlur = (event: React.FocusEvent<HTMLInputElement>) => {
		event.currentTarget.style.borderColor = 'var(--color-border-strong)';
		event.currentTarget.style.boxShadow = 'none';
		commitDraft();
		onBlur?.(event);
	};

	const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
		setDraft(event.target.value);
	};

	return (
		<div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-1-5)', ...style }}>
			<div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }} role="list">
				{tags.map((tag, index) => (
					<div
						key={`${tag}-${index}`}
						role="listitem"
						style={{
							display: 'inline-flex',
							alignItems: 'center',
							gap: 6,
							padding: '3px 8px',
							borderRadius: 'var(--radius-sm)',
							fontSize: 'var(--text-2xs)',
							fontFamily: 'var(--font-sans)',
							background: 'var(--color-accent-subtle)',
							border: '1px solid var(--color-accent-border)',
							color: 'var(--color-text-primary)',
							...chipStyle,
						}}
					>
						<span>{tag}</span>
						<button
							type="button"
							aria-label={`Remove ${tag}`}
							onClick={() => remove(index)}
							disabled={disabled}
							style={{
								display: 'inline-flex',
								alignItems: 'center',
								justifyContent: 'center',
								width: 16,
								height: 16,
								border: 'none',
								borderRadius: 'var(--radius-sm)',
								background: 'transparent',
								padding: 0,
								color: 'var(--color-text-secondary)',
								cursor: disabled ? 'not-allowed' : 'pointer',
							}}
						>
							<Icon name="x" size={12} />
						</button>
					</div>
				))}
			</div>
			<input
				type="text"
				value={draft}
				placeholder={placeholder}
				disabled={disabled}
				onChange={handleChange}
				onKeyDown={handleKeyDown}
				onFocus={handleFocus}
				onBlur={handleBlur}
				style={{
					width: '100%',
					fontFamily: 'var(--font-sans)',
					fontSize: 'var(--text-base)',
					color: 'var(--color-text-primary)',
					background: 'var(--color-surface-sunken)',
					border: '1px solid var(--color-border-strong)',
					borderRadius: 'var(--radius-sm)',
					padding: 'var(--component-input-py) var(--component-input-px)',
					minHeight: 'var(--density-input-height, 2.25rem)',
					transition:
						'border-color var(--duration-fast) var(--easing-standard), box-shadow var(--duration-fast) var(--easing-standard)',
					boxSizing: 'border-box',
					...inputStyle,
				}}
				{...rest}
			/>
			{maxTags !== Infinity && (
				<div style={{ fontSize: 'var(--text-2xs)', color: 'var(--color-text-tertiary)' }}>
					{tags.length}/{maxTags}
				</div>
			)}
		</div>
	);
}

// src/lib/ui/common/TagInput.svelte
<script lang="ts">
	interface Props {
		tags?: string[];
		label?: string;
		placeholder?: string;
		helper?: string;
		disabled?: boolean;
		id?: string;
		onchange?: (tags: string[]) => void;
	}

	let {
		tags = $bindable([]),
		label,
		placeholder = 'Add tag...',
		helper,
		disabled = false,
		id,
		onchange,
	}: Props = $props();

	let inputValue = $state('');
	let inputEl = $state<HTMLInputElement | null>(null);
	const inputId = $derived(
		id ?? (label ? `tag-input-${label.toLowerCase().replace(/\s+/g, '-')}` : 'tag-input'),
	);

	function addTag(raw: string): void {
		const value = raw.trim().toLowerCase();
		if (!value || tags.includes(value)) {
			inputValue = '';
			return;
		}
		tags = [...tags, value];
		inputValue = '';
		onchange?.(tags);
	}

	function removeTag(tag: string): void {
		tags = tags.filter((t) => t !== tag);
		onchange?.(tags);
	}

	function handleKeydown(event: KeyboardEvent): void {
		if (event.key === 'Enter' || event.key === ',') {
			event.preventDefault();
			addTag(inputValue);
			return;
		}
		if (event.key === 'Backspace' && !inputValue && tags.length > 0) {
			const last = tags[tags.length - 1];
			if (last) removeTag(last);
		}
	}

	function handleBlur(): void {
		if (inputValue.trim()) addTag(inputValue);
	}
</script>

<div class="flex flex-col gap-1">
	{#if label}
		<label for={inputId} class="text-sm font-medium text-ink">{label}</label>
	{/if}
	<div
		class="flex min-h-9 flex-wrap items-center gap-1 rounded-md border border-border bg-surface-alt px-2 py-1.5
			focus-within:ring-2 focus-within:ring-accent focus-within:ring-offset-0 focus-within:border-accent
			hover:border-border-strong transition-colors
			{disabled ? 'opacity-50 cursor-not-allowed' : ''}"
		onclick={() => inputEl?.focus()}
		role="none"
	>
		{#each tags as tag (tag)}
			<span
				class="inline-flex items-center gap-1 rounded bg-accent-subtle px-1.5 py-0.5 text-xs text-accent"
			>
				{tag}
				{#if !disabled}
					<button
						type="button"
						class="flex items-center rounded hover:text-accent-hover focus-visible:outline-accent"
						onclick={() => removeTag(tag)}
						aria-label="Remove tag {tag}"
					>
						<svg
							width="10"
							height="10"
							viewBox="0 0 12 12"
							fill="none"
							stroke="currentColor"
							stroke-width="2.5"
							stroke-linecap="round"
						>
							<line x1="2" y1="2" x2="10" y2="10"></line>
							<line x1="10" y1="2" x2="2" y2="10"></line>
						</svg>
					</button>
				{/if}
			</span>
		{/each}
		<input
			bind:this={inputEl}
			bind:value={inputValue}
			id={inputId}
			type="text"
			{placeholder}
			{disabled}
			class="min-w-20 flex-1 bg-transparent text-sm text-ink placeholder:text-ink-faint focus:outline-none"
			onkeydown={handleKeydown}
			onblur={handleBlur}
		/>
	</div>
	{#if helper}
		<p class="text-xs text-ink-muted">{helper}</p>
	{/if}
</div>
