// apps/gm-react/src/ds/components/domain/HPBar.jsx
import React from 'react';

/**
 * HPBar — hit-point meter for the combat hot path. The fill color crosses thresholds (healthy →
 * bloodied → critical) so a DM reads danger at a glance; the numeric value uses the mono face.
 * Color is reinforced by the explicit number, never the sole signal.
 */
export function HPBar({ current, max, label, size = 'md', showText = true, style, ...rest }) {
	const pct = max > 0 ? Math.max(0, Math.min(1, current / max)) : 0;
	const ratio = current / (max || 1);
	const color = ratio <= 0.25 ? 'var(--color-status-error)' : ratio <= 0.5 ? 'var(--color-status-warning)' : 'var(--color-status-success)';
	const h = size === 'sm' ? 6 : size === 'lg' ? 14 : 9;
	return (
		<div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-1)', minWidth: 0, ...style }} {...rest}>
			{(label || showText) && (
				<div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', gap: 'var(--space-2)' }}>
					{label && <span style={{ fontFamily: 'var(--font-sans)', fontSize: 'var(--text-sm)', color: 'var(--color-text-secondary)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{label}</span>}
					{showText && <span style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--text-sm)', fontWeight: 'var(--font-weight-medium)', color: ratio <= 0.25 ? 'var(--color-status-error-text)' : 'var(--color-text-primary)' }}>{current}<span style={{ color: 'var(--color-text-tertiary)' }}>/{max}</span></span>}
				</div>
			)}
			<div style={{ height: h, borderRadius: 'var(--radius-full)', background: 'var(--color-surface-sunken)', border: '1px solid var(--color-border)', overflow: 'hidden' }}>
				<div style={{ width: `${pct * 100}%`, height: '100%', background: color, borderRadius: 'var(--radius-full)', transition: 'width var(--duration-standard) var(--easing-standard), background var(--duration-standard) var(--easing-standard)' }} />
			</div>
		</div>
	);
}

// apps/gm/src/lib/gui/ux-char/HpBar.svelte
<script lang="ts">
	import { hpRatio, hpTone } from './hp-tone';

	// UX-CHAR-011 — the at-a-glance HP meter. `role="meter"` with aria-valuenow/min/max so a screen
	// reader announces the value; the fill colour encodes the tone non-redundantly (the numerals carry
	// the same information, so colour is never the only signal — WCAG 1.4.1).
	interface Props {
		hp: number;
		maxHp: number;
		tempHp?: number;
		/** Accessible name prefix, e.g. the character name, so the meter announces "Thorin hit points". */
		label: string;
		testid?: string;
	}
	const { hp, maxHp, tempHp = 0, label, testid }: Props = $props();

	const ratio = $derived(hpRatio(hp, maxHp));
	const tone = $derived(hpTone(hp, maxHp));
	const pct = $derived(Math.round(ratio * 100));
</script>

<div class="hpbar" data-testid={testid} data-tone={tone}>
	<div
		class="track"
		role="meter"
		aria-valuenow={hp}
		aria-valuemin={0}
		aria-valuemax={maxHp}
		aria-label={`${label} hit points: ${hp} of ${maxHp}`}
	>
		<div class="fill" data-tone={tone} style:width={`${pct}%`}></div>
	</div>
	<div class="numerals">
		<span class="current">{hp}</span><span class="sep">/</span><span class="max">{maxHp}</span>
		{#if tempHp > 0}
			<span class="temp" data-testid={testid ? `${testid}-temp` : undefined}>+{tempHp} temp</span>
		{/if}
	</div>
</div>

<style>
	.hpbar {
		display: flex;
		align-items: center;
		gap: var(--space-2);
		min-width: 0;
	}
	.track {
		position: relative;
		flex: 1 1 auto;
		min-width: var(--space-12);
		height: var(--space-2);
		background: var(--color-surface-sunken);
		border: 1px solid var(--color-border);
		border-radius: var(--radius-full);
		overflow: hidden;
	}
	.fill {
		height: 100%;
		border-radius: inherit;
		/* `--duration-fast` is globally zeroed under prefers-reduced-motion, so no extra query needed. */
		transition: width var(--duration-fast) var(--ease-out, ease-out);
	}
	.fill[data-tone='high'] {
		background: var(--color-status-success);
	}
	.fill[data-tone='mid'] {
		background: var(--color-status-warning);
	}
	.fill[data-tone='low'] {
		background: var(--color-status-error);
	}
	.numerals {
		display: inline-flex;
		align-items: baseline;
		gap: var(--space-0-5);
		font-variant-numeric: tabular-nums;
		font-size: var(--text-sm);
		white-space: nowrap;
	}
	.current {
		font-weight: var(--font-weight-semibold);
		color: var(--color-text-primary);
	}
	.sep,
	.max {
		color: var(--color-text-secondary);
	}
	.temp {
		margin-left: var(--space-1);
		color: var(--color-status-info-text);
		font-size: var(--text-xs);
	}
</style>
